// react_init/src/components/Pagina1.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Pagina1 extends Component {
  urlParams = () => {};

  render() {
    var nombre = this.props.match.params.nombre;
    var apellidos = this.props.match.params.apellidos;

    return (
      <React.Fragment>
        <Slider title="Párametros en la URL" size="slider-small" />
        <div className="center">
          <section id="content">
            <h2 className="subheader">Página 1: Párametros</h2>
            <h3>
              {nombre && !apellidos && (
                <span>
                  {"Su nombre es: "} {nombre}
                </span>
              )}
              {nombre && apellidos && (
                <span>
                  {"Su nombre es: "} {nombre} {apellidos}
                </span>
              )}
              {!nombre && !apellidos && (
                <span>{"No hay parámetros que mostrar"}</span>
              )}
            </h3>
            <div>
              <Link to="/pagina1/Jesse/Melara" className="btn">
                Nombre y apellidos
              </Link>
            </div>
          </section>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Pagina1;

// AngularInit/src/app/components/pagina1/pagina1.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-pagina1',
  templateUrl: './pagina1.component.html',
  styleUrls: ['./pagina1.component.css']
})
export class Pagina1Component implements OnInit {
  pg1Text = "Sección de párametros en la URL";
  public nombre!: string;
  public apellidos!: string;

  constructor( 
    private _route: ActivatedRoute,
    private _router: Router
  ) {}
    
  ngOnInit(): void {
    this._route.params.subscribe((params: Params) => {
      this.nombre = params.nombre;
      this.apellidos = params.apellidos;    
    })
  }
  
  redireccion(){
    this._router.navigate(['/pagina1', 'Jesse', 'Melara']);
  }
}

<app-slider [title]="pg1Text" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Página 1</h1>
    <div *ngIf="nombre && apellidos; then Params else noParams"></div>

    <ng-template #Params>
        <h3>Su nombre es: {{nombre}} {{apellidos}}</h3>
    </ng-template>

    <ng-template #noParams>
        <h3>No hay parámetros que mostrar</h3>
    </ng-template>

    <div>
        <button class="btn" (click)="redireccion()">Nombre y apellidos</button>
    </div>
  </section>
  
  <app-sidebar></app-sidebar>
</div>
