// react_init/src/App.js
import React from "react";
import "./assets/css/App.css";

//Componentes
import Header from "./components/Header";
import Slider from "./components/Slider";
import Sidebar from "./components/Sidebar";
import Footer from "./components/Footer";
import Router from "./Router";

function App() {
  return (
    <div className="App">
      <Header />
      <Slider />

      <div className="center">
        <section>
          <Router />
        </section>
        <Sidebar />
      </div>
      <Footer />
      <header className="App-header"></header>
    </div>
  );
}

export default App;

// vue_init/src/App.vue
<template>
  <div id="app">
    <Header />
    <Slider />
    <div class="center">
      <section id="content">
        <router-view></router-view>
      </section>
      <Sidebar />
      <div class="clearfix"></div>
    </div>
    <Footer />
  </div>
</template>

<script>
import Header from "./components/Header.vue";
import Slider from "./components/Slider.vue";
import Sidebar from "./components/Sidebar.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "App",
  components: {
    Header,
    Slider,
    Sidebar,
    Footer,
  },
};
</script>

<style>
@import "./assets/css/styles.css";
</style>
