// vue_init/src/components/Articles.vue
<template>
  <div v-if="!articles" ref="divContainer">
    <h3 class="subheader">Preparando contenido</h3>
    <p>
      Espere mientras cargan los complementos. Caso contrario, intente más
      tarde.
    </p>
  </div>
  <div v-if="articles && articles.length <= 1">
    <h3 class="subheader">Sin resultados</h3>
    <p>No hay artículos para mostrar. Intente más tarde.</p>
  </div>
  <div v-if="articles && articles.length >= 1" ref="divContainer">
    <article
      class="article-item"
      id="article-template"
      v-for="article in articles"
      :key="article._id"
    >
      <div class="image-wrap">
        <img
          :src="url + 'get-image/' + article.image"
          :alt="article.title"
          v-if="article.image"
        />
        <img
          src="../assets/images/default-image.svg"
          :alt="article.title"
          v-else
        />
      </div>
      <h2>{{ article.title }}</h2>
      <span class="date">
        {{
          moment(article.date)
            .fromNow()[0]
            .toUpperCase() +
            moment(article.date)
              .fromNow()
              .slice(1)
        }}
      </span>
      <router-link :to="{ name: 'article', params: { id: article._id } }"
        >Leer más</router-link
      >

      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
import Global from "../Global";
import moment from "moment";

export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
      isLoading: false,
      moment: moment,
    };
  },
  mounted() {
    let loader = this.$loading.show({
      // Optional parameters
      container: this.$refs.divContainer,
      canCancel: true,
      onCancel: this.onCancel,
    });
    // simulate AJAX
    setTimeout(() => {
      loader.hide();
    }, 900);
  },
  methods: {
    onCancel() {
      console.log("El usuario interrumpió la carga.");
    },
  },
};
</script>

// react_init/src/components/Articles.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import Moment from "react-moment";
import "moment/locale/es";
import Global from "../Global";
import defaultImage from "../assets/images/default-image.svg";

export default class Articles extends Component {
  url = Global.url;

  state = {
    articles: [],
    status: null,
  };

  componentDidMount() {
    this.getArticle();
  }

  getArticle = () => {
    axios.get(this.url + "articles").then((res) => {
      console.log(res.data);

      this.setState({
        articles: res.data.articles,
        status: "success",
      });

      console.log(this.state);
    });
  };

  render() {
    if (this.state.articles.length >= 1) {
      let showArticles = this.state.articles.map((article) => {
        return (
          <article className="article-item" key={article._id}>
            <div className="image-wrap">
              {article.image !== null ? (
                <img
                  src={this.url + "get-image/" + article.image}
                  alt={article.title}
                />
              ) : (
                <img src={defaultImage} alt={article.title} />
              )}
            </div>
            <h2 className="subheader">{article.title}</h2>
            <span className="date">
              Actualizado:{" "}
              <Moment locale="es" fromNow>
                {article.date}
              </Moment>
            </span>
            <Link to={"/blog/article/" + article._id}>Leer más</Link>

            <div className="clearfix"></div>
          </article>
        );
      });

      return <div id="articles">{showArticles}</div>;
    } else if (
      this.state.articles.length === 0 &&
      this.state.status === "success"
    ) {
      return (
        <div id="articles">
          <h2 className="subheader">No hay artículos para mostrar</h2>
          <p>Todavía no se ha creado ningún contenido para esta sección</p>
        </div>
      );
    } else {
      return (
        <div id="articles">
          <h2 className="subheader">Preparando artículos...</h2>
          <p>Espere mientras carga el contenido</p>
        </div>
      );
    }
  }
}
