// AngularInit/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  homeText = "Bienvenido al Master en Angular JS";
  public title: string;

  constructor() { 
    this.title = "Últimos Artículos";
  }
  ngOnInit(): void {
  }

}

<app-slider [title]="homeText"></app-slider>

<div class="center">
  <section id="content">
    <h2 class="subheader">{{title}}</h2>
    
  </section>
  
  <app-sidebar></app-sidebar>
</div>

// react_init/src/components/Home.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Home extends Component {
  render() {
    return (
      <React.Fragment>
        <Slider
          title="Bienvenido al Master en ReactJS"
          size="slider-big"
          btn="true"
        />
        <div className="center">
          <section id="content">
            <h1 className="subheader">Últimos Artículos</h1>
          </section>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Home;
