// AngularInit/src/app/components/search/search.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.css'],
  providers: [ArticleService]
})
export class SearchComponent implements OnInit {
  public searchText:string = "Búsqueda";
  public articles!: Article[];

  constructor(
    private _route: ActivatedRoute,
    private _router: Router,
    private articleService: ArticleService
  ) { }

  ngOnInit(): void {
    this._route.params.subscribe(params => {
      let search = params['search'];

      this.articleService.search(search).subscribe(
        response => {
          if(response.articles){
            this.articles = response.articles;
            console.log(this.articles);
          }
        },
        error => {
          console.log(error);
          this.articles = [];
                }
      )
    })
  }

}

<app-slider [title]="searchText" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Resultados de búsqueda</h1>
    
    <app-articles [articles]="articles"></app-articles>

  </section>
  
  <app-sidebar></app-sidebar>
</div>

// react_init/src/components/Search.js
import React, { Component } from "react";
import Slider from "./Slider";
import Articles from "./Articles";
import Sidebar from "./Sidebar";

export default class Search extends Component {
  render() {
    let searchText = this.props.match.params.search;
    return (
      <React.Fragment>
        <Slider title={"Búsqueda: " + searchText} size="slider-small" />
        <div className="center">
          <h2 className="subheader">Búsqueda</h2>
          <div id="content">
            <Articles search={searchText} />
          </div>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}
