// vue_init/src/components/Sidebar.vue
<template>
    <aside id="sidebar">
        <div id="nav-blog" class="sidebar-item">
            <h3>Puedes hacer esto</h3>
            <a href="#" class="btn btn-success">Crear artículo</a>
        </div>

        <div id="search" class="sidebar-item">
            <h3>Buscador</h3>
            <p>Encuentra el artículo que buscas</p>
            <input type="text" name="search">
            <input class="btn" type="submit" value="Buscar">
        </div>
    </aside>
</template>

<script>
export default {
    name: 'Sidebar'
}
</script>

// react_init/src/components/Sidebar.js
import React, { Component } from "react";

class Sidebar extends Component {
  render() {
    return (
      <React.Fragment>
        <aside id="sidebar">
          <div id="nav-blog" className="sidebar-item">
            <h3>Puedes hacer esto</h3>
            <a href="prueba.html" className="btn btn-success">
              Crear artículo
            </a>
          </div>

          <div id="search" className="sidebar-item">
            <h3>Buscador</h3>
            <p>Encuentra el artículo que buscas</p>
            <input type="text" name="search" />
            <input className="btn" type="submit" value="Buscar" />
          </div>
        </aside>

        <div class="clearfix"></div>
      </React.Fragment>
    );
  }
}

export default Sidebar;
