// react_init/src/components/ArticleEdit.js
import React, { Component } from "react";
import { Redirect } from "react-router-dom";
import SimpleReactValidator from "simple-react-validator";
import axios from "axios";
import Swal from "sweetalert2";
import Global from "../Global";
import Sidebar from "./Sidebar";
import defaultImage from "../assets/images/default-image.svg";

export default class ArticleEdit extends Component {
  url = Global.url;
  articleId = null;

  titleRef = React.createRef();
  contentRef = React.createRef();

  state = {
    article: [],
    status: null,
    fileImage: null,
    selectedFile: null,
  };

  componentDidMount() {
    this.getArticle(this.articleId);
  }

  constructor(props) {
    super(props);
    this.articleId = this.props.match.params.id;
    this.validator = new SimpleReactValidator({
      autoForceUpdate: this,
      messages: {
        regex: "Este campo solo admite letras, acentos y espacios.",
        required: "Este campo es requerido.",
      },
    });
  }

  getArticle = (id) => {
    axios.get(this.url + "article/" + id).then((res) => {
      this.setState({
        article: res.data.article,
      });
    });
  };

  changeState = () => {
    this.setState({
      article: {
        title: this.titleRef.current.value,
        content: this.contentRef.current.value,
        image: this.state.article.image,
      },
    });
  };

  fileUpload = (event) => {
    this.setState({
      fileImage: URL.createObjectURL(event.target.files[0]),
      selectedFile: event.target.files[0],
    });

    // console.log(this.state.selectedFile);
  };

  saveArticle = (e) => {
    e.preventDefault();

    // Rellenar state con formulario
    this.changeState();
    if (this.validator.allValid()) {
      // Alerta para Guardar articulo
      Swal.fire({
        title: "¿Quieres guardar los cambios realizados?",
        showDenyButton: true,
        showCancelButton: true,
        confirmButtonText: `Guardar`,
        denyButtonText: `No Guardar`,
        cancelButtonText: `Cancelar`,
      }).then((result) => {
        /* Read more about isConfirmed, isDenied below */
        if (result.isConfirmed) {
          Swal.fire("El artículo ha sido actualizado", "", "success");
          // Hacer una peticion HTTP por POST para guardar el articulo
          axios
            .put(this.url + "article/" + this.articleId, this.state.article)
            .then((res) => {
              console.log(res.data);

              if (res.data.article) {
                this.setState({
                  article: res.data.article,
                  status: "waiting",
                });

                //Subir imagen
                if (this.state.selectedFile !== null) {
                  //Sacar el id del articulo guardado
                  let articleId = this.state.article._id;

                  //Crear form data y agregar el fichero
                  const formData = new FormData();
                  formData.append(
                    "file0",
                    this.state.selectedFile,
                    this.state.selectedFile.name
                  );

                  //Peticion AJAX
                  axios
                    .post(this.url + "upload-image/" + articleId, formData)
                    .then((res) => {
                      console.log(res.data);
                      if (res.data.article.image) {
                        this.setState({
                          article: res.data.article,
                          status: "success",
                        });
                      } else {
                        this.setState({
                          article: res.data.article,
                          status: "success",
                        });
                      }
                    })
                    .catch((err) => {
                      if (err.response) {
                        console.log(err.response.data);
                        console.log(err.response.status);
                      } else if (err.request) {
                        console.log(err.request);
                      } else {
                        console.log("Error", err.message);
                      }
                      console.log(err.config);
                    });
                } else {
                  this.setState({
                    status: "success",
                  });
                }
              } else {
                this.setState({
                  status: "error",
                });
              }
            });
        } else if (result.isDenied) {
          Swal.fire("Los cambios efectuados no se han guardado", "", "info");
          return <Redirect to={"/blog/edit/" + this.articleId} />;
        }
      });
    } else {
      this.setState({
        status: "error",
      });
      this.validator.showMessages();
    }
  };

  render() {
    if (this.state.status === "success") {
      console.log(this.state);
      return <Redirect to={"/blog/article/" + this.state.article._id} />;
    }

    let article = this.state.article;

    return (
      <div className="center">
        <section id="content">
          <h1 className="subheader">Editar Artículo</h1>
          {this.state.article ? (
            <form className="mid-form" onSubmit={this.saveArticle}>
              <div className="form-group">
                <label htmlFor="title">Título</label>
                <input
                  type="text"
                  name="title"
                  defaultValue={article.title}
                  ref={this.titleRef}
                  onChange={this.changeState}
                  onBlur={() => this.validator.showMessageFor("regex")}
                />

                {/*** Validación de campo ***/}
                {this.validator.message(
                  "title",
                  this.state.article.title,
                  "required|regex:^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\u0020*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$",
                  { className: "text-danger" }
                )}
              </div>

              <div className="form-group">
                <label htmlFor="content">Contenido</label>
                <textarea
                  name="content"
                  defaultValue={article.content}
                  ref={this.contentRef}
                  onChange={this.changeState}
                  onBlur={() => this.validator.showMessageFor("required")}
                ></textarea>

                {/*** Validación de campo ***/}
                {this.validator.message(
                  "content",
                  this.state.article.content,
                  "required",
                  { className: "text-danger" }
                )}
              </div>

              <div className="form-group">
                <label htmlFor="image">Imagen</label>
                <div className="image-wrap">
                  {/*** Imagen de articulo a editar ***/}
                  {this.state.fileImage ? (
                    <img
                      src={this.state.fileImage}
                      alt={article.title}
                      style={{
                        width: "250px",
                        height: "115px",
                        margin: "10px",
                      }}
                    />
                  ) : article.image !== null ? (
                    <img
                      src={this.url + "get-image/" + article.image}
                      alt={article.title}
                      style={{
                        width: "250px",
                        height: "115px",
                        margin: "10px",
                      }}
                    />
                  ) : (
                    <img
                      src={defaultImage}
                      alt={article.title}
                      style={{ width: "170px", height: "95px", margin: "10px" }}
                    />
                  )}
                </div>
                <br />
                <input type="file" name="image" onChange={this.fileUpload} />
              </div>
              <div className="clearfix"></div>
              <input
                type="submit"
                value="Guardar"
                className="btn btn-primary"
              />
            </form>
          ) : (
            <React.Fragment>
              <h2 className="subheader">Cargando...</h2>
              <p>Espere mientras carga el contenido</p>
            </React.Fragment>
          )}
        </section>

        <Sidebar />
      </div>
    );
  }
}

// vue_init/src/components/ArticleEdit.vue
<template>
  <section>
    <div class="center">
      <section id="content">
        <h2 class="subheader">Editar Artículo</h2>

        <form class="mid-form" @submit.prevent="saveArticle">
          <div class="form-group">
            <label :for="form.article.title.$uid">Título</label>
            <input
              type="text"
              name="title"
              v-model="form.article.title.$value"
            />
            <div class="text-danger" v-if="errors.length > 0">
              <p v-for="(error, i) in form.article.title.$errors" :key="i">
                {{ error }}
              </p>
            </div>
          </div>

          <div class="form-group">
            <label :for="form.article.content.$uid">Contenido</label>
            <textarea
              name="content"
              v-model="form.article.content.$value"
            ></textarea>
            <div class="text-danger" v-if="errors.length > 0">
              <p v-for="(error, i) in form.article.content.$errors" :key="i">
                {{ error }}
              </p>
            </div>
          </div>

          <div class="form-group">
            <label for="image">Imagen</label>
            <input
              type="file"
              id="image"
              name="file"
              ref="file"
              @change="onFileChange"
            />
            <div class="image-wrap">
              <img
                :src="pathImage"
                :alt="pathImage"
                style="width:250px; height:115px; margin:5px;"
                v-if="pathImage"
              />
              <img
                :src="url + 'get-image/' + imageName"
                :alt="form.article.title.$value"
                style="width:250px; height:115px; margin:5px;"
                v-else-if="imageName"
              />
              <img
                src="../assets/images/default-image.svg"
                :alt="form.article.title.$value"
                style="width:250px; height:115px; margin:5px;"
                v-else
              />
            </div>
          </div>
          <br />

          <div class="clearfix"></div>
          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>
      </section>
      <Sidebar />
      <div class="clearfix"></div>
    </div>
  </section>
</template>
<script>
import Sidebar from "./Sidebar.vue";
import Global from "../Global";
import axios from "axios";
import Swal from "sweetalert2";
import { useRoute, useRouter } from "vue-router";
import { onMounted, ref } from "vue";
import { useValidation, ValidationError } from "vue3-form-validation";
export const required = (msg) => (x) => !x && msg;
const newLocal = /^[a-zA-ZÀ-ÿ\u00f1\u00d1]+(\u0020*[a-zA-ZÀ-ÿ\u00f1\u00d1]*)*[a-zA-ZÀ-ÿ\u00f1\u00d1]+$/;
export const regex = (msg) => (x) => newLocal.test(x) || msg;

export default {
  name: "ArticleCreate",
  components: {
    Sidebar,
  },
  props: {
    id: String,
    imageName: String,
  },
  data() {
    return {
      pathImage: null,
    };
  },
  methods: {
    onFileChange(e) {
      const fileRoot = e.target.files[0];
      this.pathImage = URL.createObjectURL(fileRoot);
      console.log(this.pathImage);
      this.fileChange();
    },
  },
  setup(props) {
    const url = Global.url;
    const file = ref(null);
    let article = null;
    let image = null;
    const route = useRoute();
    const router = useRouter();
    const {
      form,
      errors,
      submitting,
      validateFields,
      resetFields,
    } = useValidation({
      article: {
        title: {
          $value: "",
          $rules: [
            required("Este campo es requerido."),
            regex("Este campo solo admite letras, acentos y espacios."),
          ],
        },
        content: {
          $value: "",
          $rules: [required("Este campo es requerido.")],
        },
      },
    });

    onMounted(() => {
      let articleId = route.params.id;
      getArticle(articleId);
    });

    async function getArticle(articleId) {
      try {
        axios
          .get(`${url}article/${articleId}`)
          .then((res) => {
            if (res.data.status == "success") {
              article = res.data.article;
              form.article.title.$value = article.title;
              form.article.content.$value = article.content;
            }
            console.log(res.data);
          })
          .catch(function(error) {
            if (error.response) {
              console.log(error.response.data);
            } else {
              console.log("Error", error.message);
            }
            console.log(error.config);
          });
      } catch (e) {
        if (e instanceof ValidationError) {
          console.log(e.message);
        }
      }
    }

    async function fileChange() {
      try {
        image = file.value.files[0];
      } catch (e) {
        if (e instanceof ValidationError) {
          console.log(e.message);
        }
      }
    }

    async function saveArticle() {
      try {
        const formData = await validateFields();
        console.log(formData);

        Swal.fire({
          title: "¿Quieres guardar este nuevo artículo?",
          showDenyButton: true,
          showCancelButton: true,
          confirmButtonText: `Guardar`,
          denyButtonText: `No Guardar`,
          cancelButtonText: `Cancelar`,
        }).then((result) => {
          /* Read more about isConfirmed, isDenied below */
          if (result.isConfirmed) {
            //Guardar datos en el Backend
            axios
              .put(`${url}article/${props.id}`, formData.article)
              .then((res) => {
                console.log(res.data);
                if (res.data.status == "success") {
                  if (image != null && image != undefined && image != "") {
                    //Subida de imagen
                    const imageData = new FormData();
                    imageData.append("file0", image, image.name);
                    let articleId = res.data.article._id;

                    //Peticion AJAX
                    axios
                      .post(`${url}upload-image/${articleId}`, imageData)
                      .then((res) => {
                        if (res.data.article) {
                          formData.article = res.data.article;
                          router.push({
                            name: "article",
                            params: { id: article._id },
                          });
                        }
                      })
                      .catch(function(error) {
                        if (error.response) {
                          console.log(error.response.data);
                          console.log(error.response.status);
                        } else {
                          console.log("Error", error.message);
                        }
                        console.log(error.config);
                      });
                  } else {
                    formData.article = res.data.article;
                    router.push({
                      name: "article",
                      params: { id: article._id },
                    });
                  }
                }
              })
              .catch(function(error) {
                if (error.response) {
                  console.log(error.response.data);
                  console.log(error.response.status);
                } else {
                  console.log("Error", error.message);
                }
                console.log(error.config);
              }); //End --Articulos guardados--

            Swal.fire(
              "¡Los cambios se han realizado exitosamente!",
              "",
              "success"
            );
          } else if (result.isDenied) {
            if (props.imageName) {
              router.push({
                name: "ArticleEdit",
                params: { id: article._id, imageName: article.image },
              });
            } else {
              router.push({
                name: "ArticleEdit",
                params: { id: article._id },
              });
            }
            Swal.fire("!Los cambios no se han guardado!", "", "info");
          }
        });
      } catch (e) {
        if (e instanceof ValidationError) {
          console.log(e.message);
        }
      }
    }

    return {
      form,
      errors,
      submitting,
      url,
      article,
      file,
      image,
      resetFields,
      getArticle,
      fileChange,
      saveArticle,
    };
  },
};
</script>
