// AngularInit/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Article } from 'src/app/models/article';
import { Global } from 'src/app/services/global';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {
  @Input() articles!: Article[];
  public url!: string;

  constructor() {
    this.url = Global.url;
  }

  ngOnInit(): void {
  }

}

<div *ngIf="!articles">
    <img class="animate__animated animate__rotateOut animate__slower animate__infinite" src="assets/images/loading.svg" alt="Cargando articulos" height="160px" width="160px">
    <br><span style="font-size: 25px;">Preparando artículos...</span>
</div>

<div *ngIf="articles && articles.length==0">
    <img class="animate__animated animate__headShake" src="assets/images/clouderror.svg" alt="Cargando articulos" height="120px" width="170px">
    <br><span style="font-size: 25px;">No se encontraron resultados para mostrar</span>
</div>

<div id="articles" *ngIf="articles">
    <article class="article-item" *ngFor="let article of articles">
        <div class="image-wrap">
            <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
            <img src="assets/images/default-color.png" alt="{{article.title}}" *ngIf="!article.image">
        </div>
        <h2>{{article.title}}</h2>
        <span class="date">
            Actualizado: {{article.date | amLocale: 'es' | amTimeAgo}}
        </span>
        <a [routerLink]="['/blog/article', article._id]">Leer más</a>

        <div class="clearfix"></div>
    </article>
</div>

// vue_init/src/components/Articles.vue
<template>
  <article
    class="article-item"
    id="article-template"
    v-for="article in articles"
    :key="article._id"
  >
    <div class="image-wrap">
      <img
        :src="url + 'get-image/' + article.image"
        :alt="article.title"
        v-if="article.image"
      />
      <img
        src="../assets/images/default-image.svg"
        :alt="article.title"
        v-else
      />
    </div>
    <h2>{{ article.title }}</h2>
    <span class="date">
      Hace 5 minutos
    </span>
    <a href="article.html">Leer más</a>

    <div class="clearfix"></div>
  </article>
</template>

<script>
import Global from "../Global";

export default {
  name: "Articles",
  props: ["articles"],
  data() {
    return {
      url: Global.url,
    };
  },
};
</script>
