// react_init/src/components/Article.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import Moment from "react-moment";
import "moment/locale/es";

import defaultImage from "../assets/images/default-image.svg";
import Sidebar from "./Sidebar";
import Global from "../Global";

export default class Article extends Component {
  url = Global.url;

  state = {
    article: false,
    status: null,
  };

  componentDidMount() {
    this.getArticle();
  }

  getArticle = () => {
    let id = this.props.match.params.id;

    axios
      .get(this.url + "article/" + id)
      .then((res) => {
        console.log(res.data);

        this.setState({
          article: res.data.article,
          status: "success",
        });
      })
      .catch((err) => {
        this.setState({
          article: false,
          status: "success",
        });
      });
  };

  render() {
    let article = this.state.article;
    let status = this.state.status;

    return (
      <div className="center">
        <section id="content">
          {article && (
            <div id="articles">
              <article className="article-item article-detail">
                <h1 className="subheader">{article.title}</h1>
                <span className="date">
                  Actualizado:{" "}
                  <Moment locale="es" fromNow>
                    {article.date}
                  </Moment>
                </span>
                <div className="image-wrap">
                  {article.image !== null ? (
                    <img
                      src={this.url + "get-image/" + article.image}
                      alt={article.title}
                    />
                  ) : (
                    <img src={defaultImage} alt={article.title} />
                  )}
                </div>
                <p>{article.content}</p>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure
                  illo, vitae quod possimus, facilis voluptates voluptatum aut
                  non qui iste quia temporibus dolore accusamus odio libero
                  magni fugiat. Hic, a.
                </p>
                <p>
                  Suscipit architecto, velit explicabo nihil asperiores
                  accusantium repellendus cumque maiores! Suscipit a error,
                  sapiente voluptas sit asperiores repellendus aspernatur,
                  autem, temporibus minima nemo maxime fugiat rerum fuga.
                  Voluptatibus, laudantium beatae! Velit cumque culpa dolorem
                  possimus explicabo a reprehenderit, assumenda quo eaque
                  repudiandae, eos omnis autem suscipit, totam tempora!
                </p>
                <p>
                  Dolorum reprehenderit quo dolores maxime architecto
                  exercitationem sequi voluptatem inventore nulla quis? Adipisci
                  quod placeat molestias excepturi quaerat corrupti nulla
                  reprehenderit possimus sit, quasi repudiandae delectus iste
                  quidem vero quisquam, laudantium officia nemo! Consequuntur
                  fugit aut cumque quod saepe debitis, perspiciatis quam!
                </p>
                <p>
                  Aliquam nulla illum fugiat repellendus non blanditiis ipsa
                  necessitatibus aut voluptatum aperiam libero, quis accusamus.
                  Quas rem, dolores, minima doloremque nobis blanditiis quam
                  sequi laudantium iste iure, consequuntur cum?
                </p>

                <div className="clearfix"></div>
              </article>
              <div className="buttons">
                <Link to="" className="btn btn-danger">
                  Editar
                </Link>
                <Link to="" className="btn btn-warning">
                  Eliminar
                </Link>
              </div>
              <div className="clearfix"></div>
            </div>
          )}

          {!article && status === "success" && (
            <div id="article">
              <h2 className="subheader">El artículo no existe</h2>
              <p>Intente de nuevo más tarde</p>
            </div>
          )}

          {status === null && (
            <div id="article">
              <h2 className="subheader">Preparando artículo...</h2>
              <p>Espere mientras carga el contenido</p>
            </div>
          )}
        </section>
        <Sidebar />
      </div>
    );
  }
}

// vue_init/src/components/Article.vue
<template>
  <div class="center">
    <section id="content">
      <div id="articles">
        <article class="article-item article-detail" v-if="article">
          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date">
            {{
              moment(article.date)
                .fromNow()[0]
                .toUpperCase() +
                moment(article.date)
                  .fromNow()
                  .slice(1)
            }}
          </span>
          <div class="image-wrap">
            <img
              :src="url + 'get-image/' + article.image"
              :alt="article.title"
              v-if="article.image"
            />
            <img
              src="../assets/images/default-image.svg"
              :alt="article.title"
              v-else
            />
          </div>
          <p>{{ article.content }}</p>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure illo,
            vitae quod possimus, facilis voluptates voluptatum aut non qui iste
            quia temporibus dolore accusamus odio libero magni fugiat. Hic, a.
          </p>
          <p>
            Suscipit architecto, velit explicabo nihil asperiores accusantium
            repellendus cumque maiores! Suscipit a error, sapiente voluptas sit
            asperiores repellendus aspernatur, autem, temporibus minima nemo
            maxime fugiat rerum fuga. Voluptatibus, laudantium beatae!
          </p>
          <p>
            Velit cumque culpa dolorem possimus explicabo a reprehenderit,
            assumenda quo eaque repudiandae, eos omnis autem suscipit, totam
            tempora! Dolorum reprehenderit quo dolores maxime architecto
            exercitationem sequi voluptatem inventore nulla quis?
          </p>
          <p>
            Adipisci quod placeat molestias excepturi quaerat corrupti nulla
            reprehenderit possimus sit, quasi repudiandae delectus iste quidem
            vero quisquam, laudantium officia nemo! Consequuntur fugit aut
            cumque quod saepe debitis, perspiciatis quam!
          </p>
          <p>
            Aliquam nulla illum fugiat repellendus non blanditiis ipsa
            necessitatibus aut voluptatum aperiam libero, quis accusamus. Quas
            rem, dolores, minima doloremque nobis blanditiis quam sequi
            laudantium iste iure, consequuntur cum?
          </p>
          <div className="buttons">
            <button class="btn btn-warning">
              Editar
            </button>
            <button class="btn btn-danger">
              Eliminar
            </button>
          </div>
          <div className="clearfix"></div>
        </article>
        <article v-else>
          <h1 class="subheader">Artículo no encontrado</h1>
          <p>El artículo no fue encontrado. Intente más tarde.</p>
        </article>
      </div>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar.vue";
import Global from "../Global";
import axios from "axios";
import moment from "moment";
import { useRouter } from "vue-router";

export default {
  name: "Article",
  components: {
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
      moment: moment,
      useRouter,
    };
  },
  mounted() {
    let articleId = this.$route.params.id;
    this.oneArticle(articleId);
  },
  methods: {
    oneArticle(articleId) {
      axios
        .get(`${this.url}article/${articleId}`)
        .then((res) => {
          if (res.data.status == "success") {
            this.article = res.data.article;
          }
          console.log(res.data);
        })
        .catch(function(error) {
          if (error.response) {
            console.log(error.response.data);
            console.log(error.response.status);
            console.log(error.response.headers);
          } else if (error.request) {
            console.log(error.request);
          } else {
            console.log("Error", error.message);
          }
          console.log(error.config);
        });
    },
  },
};
</script>
