// react_init/src/components/Blog.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Blog extends Component {
  render() {
    return (
      <React.Fragment>
        <Slider title="Blog" size="slider-small" />
        <div className="center">
          <section id="content">
            <h1 className="subheader">Blog</h1>
          </section>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Blog;

// vue_init/src/components/Blog.vue
<template>
  <Slider title="Blog" size="slider-small" />
  <div class="center">
    <section id="content">
      <h2 class="subheader">Blog</h2>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Blog",
  components: {
    Slider,
    Sidebar,
  },
};
</script>
