// react_init/src/components/Home.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Home extends Component {
  render() {
    return (
      <React.Fragment>
        <Slider
          title="Bienvenido al Master en ReactJS"
          size="slider-big"
          btn="true"
        />
        <div className="center">
          <section id="content">
            <h1 className="subheader">Últimos Artículos</h1>
          </section>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Home;

// vue_init/src/components/Home.vue
<template>
  <Slider title="Bienvenido al Master en VueJS" size="slider-big" home="true" />
  <div class="center">
    <section id="content">
      <h2 class="subheader">Últimos artículos</h2>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Home",
  components: {
    Slider,
    Sidebar,
  },
};
</script>
