// react_init/src/components/Pagina1.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Pagina1 extends Component {
  urlParams = () => {};

  render() {
    var nombre = this.props.match.params.nombre;
    var apellidos = this.props.match.params.apellidos;

    return (
      <React.Fragment>
        <Slider title="Párametros en la URL" size="slider-small" />
        <div className="center">
          <section id="content">
            <h2 className="subheader">Página 1: Párametros</h2>
            <h3>
              {nombre && !apellidos && (
                <span>
                  {"Su nombre es: "} {nombre}
                </span>
              )}
              {nombre && apellidos && (
                <span>
                  {"Su nombre es: "} {nombre} {apellidos}
                </span>
              )}
              {!nombre && !apellidos && (
                <span>{"No hay parámetros que mostrar"}</span>
              )}
            </h3>
            <div>
              <Link to="/pagina1/Jesse/Melara" className="btn">
                Nombre y apellidos
              </Link>
            </div>
          </section>

          <Sidebar />
        </div>
      </React.Fragment>
    );
  }
}

export default Pagina1;

// vue_init/src/components/Pagina1.vue
<template>
  <Slider title="Párametros en la URL" size="slider-small" />
  <div class="center">
    <section id="content">
      <h2 class="subheader">Página 1: Párametros en la URL</h2>
      <div v-if="!nombre && !apellido">
        <p>
          No se encuentran párametros para mostrar
        </p>

        <input type="text" v-model="nombres" style="width: 80%;" />
        <p v-if="nombres">
          Su nombre es: <em>{{ nombres }}</em>
        </p>
      </div>

      <p v-if="nombre || apellido">
        Su nombre es: <em>{{ nombre }} {{ apellido }}</em>
      </p>

      <div class="btnParams">
        <router-link to="/pagina1/Jesse/Melara" class="btn"
          >Nombre y apellidos</router-link
        >
      </div>
      <div class="clearfix"></div>
      <div class="btnParams">
        <button @click="notFoundPage()" class="btn btn-danger">
          Página Error
        </button>
      </div>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Pagina1",
  components: {
    Slider,
    Sidebar,
  },
  mounted() {
    this.nombre = this.$route.params.nombre;
    this.apellido = this.$route.params.apellido;
  },
  updated() {
    this.nombre = this.$route.params.nombre;
    this.apellido = this.$route.params.apellido;
  },
  data() {
    return {
      nombre: null,
      apellido: null,
      nombres: "",
    };
  },
  methods: {
    notFoundPage() {
      this.$router.push({
        name: "NotFound",
        params: { pathMatch: "not-found" },
      });
    },
  },
};
</script>
