// react_init/src/components/Sidebar.js
import React, { Component } from "react";

class Sidebar extends Component {
  render() {
    return (
      <React.Fragment>
        <aside id="sidebar">
          <div id="nav-blog" className="sidebar-item">
            <h3>Puedes hacer esto</h3>
            <a href="prueba.html" className="btn btn-success">
              Crear artículo
            </a>
          </div>

          <div id="search" className="sidebar-item">
            <h3>Buscador</h3>
            <p>Encuentra el artículo que buscas</p>
            <input type="text" name="search" />
            <input className="btn" type="submit" value="Buscar" />
          </div>
        </aside>

        <div class="clearfix"></div>
      </React.Fragment>
    );
  }
}

export default Sidebar;

// AngularInit/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {
  public searchString!: string;

  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ) { }

  ngOnInit(): void {
  }

  goSearch(){
    this._router.navigate(['/search', this.searchString]);
  }
}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="#" class="btn btn-success">Crear artículo</a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el artículo que buscas</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()" [(ngModel)="searchString"]>
            <input type="text" name="search">
            <input class="btn" type="submit" value="Buscar">
        </form>
    </div>
</aside>

<div class="clearfix"></div>
