// react_init/src/components/Article.js
import React, { Component } from "react";
import { Link, Redirect } from "react-router-dom";
import axios from "axios";
import Moment from "react-moment";
import "moment/locale/es";
import Swal from "sweetalert2";

import defaultImage from "../assets/images/default-image.svg";
import Sidebar from "./Sidebar";
import Global from "../Global";

export default class Article extends Component {
  url = Global.url;

  state = {
    article: false,
    status: null,
  };

  componentDidMount() {
    this.getArticle();
  }

  getArticle = () => {
    let id = this.props.match.params.id;

    axios
      .get(this.url + "article/" + id)
      .then((res) => {
        console.log(res.data);

        this.setState({
          article: res.data.article,
          status: "success",
        });
      })
      .catch((err) => {
        this.setState({
          article: false,
          status: "success",
        });
      });
  };

  deleteArticle = (id) => {
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: "btn btn-primary",
        cancelButton: "btn btn-secondary",
      },
      buttonsStyling: false,
    });

    swalWithBootstrapButtons
      .fire({
        title: "¿Estás seguro que quieres eliminar este artículo?",
        text: "¡Esta acción es irreversible!",
        icon: "warning",
        showCancelButton: true,
        confirmButtonText: "Sí, ¡elimínalo!",
        cancelButtonText: "No, ¡cancelar!",
        reverseButtons: true,
      })
      .then((result) => {
        if (result.isConfirmed) {
          axios.delete(this.url + "article/" + id).then((res) => {
            this.setState({
              article: res.data.article,
              status: "deleted",
            });
            swalWithBootstrapButtons.fire(
              "¡Artículo eliminado!",
              "Este artículo fue eliminado exitosamente",
              "success"
            );
          });
        } else if (
          /* Read more about handling dismissals below */
          result.dismiss === Swal.DismissReason.cancel
        ) {
          swalWithBootstrapButtons.fire(
            "Acción cancelada",
            "Tranquilo, ¡el artículo está a salvo!",
            "error"
          );
          this.setState({
            status: "cancelled",
          });
          return <Redirect to={"/blog/article/" + id} />;
        }
      });
  };

  render() {
    let article = this.state.article;
    let status = this.state.status;

    if (this.state.status === "deleted") {
      return <Redirect to={"/blog"} />;
    }

    return (
      <div className="center">
        <section id="content">
          {article && (
            <div id="articles">
              <article className="article-item article-detail">
                <h1 className="subheader">{article.title}</h1>
                <span className="date">
                  Actualizado:{" "}
                  <Moment locale="es" fromNow>
                    {article.date}
                  </Moment>
                </span>
                <div className="image-wrap">
                  {article.image !== null ? (
                    <img
                      src={this.url + "get-image/" + article.image}
                      alt={article.title}
                    />
                  ) : (
                    <img src={defaultImage} alt={article.title} />
                  )}
                </div>
                <p>{article.content}</p>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure
                  illo, vitae quod possimus, facilis voluptates voluptatum aut
                  non qui iste quia temporibus dolore accusamus odio libero
                  magni fugiat. Hic, a.
                </p>
                <p>
                  Suscipit architecto, velit explicabo nihil asperiores
                  accusantium repellendus cumque maiores! Suscipit a error,
                  sapiente voluptas sit asperiores repellendus aspernatur,
                  autem, temporibus minima nemo maxime fugiat rerum fuga.
                  Voluptatibus, laudantium beatae! Velit cumque culpa dolorem
                  possimus explicabo a reprehenderit, assumenda quo eaque
                  repudiandae, eos omnis autem suscipit, totam tempora!
                </p>
                <p>
                  Dolorum reprehenderit quo dolores maxime architecto
                  exercitationem sequi voluptatem inventore nulla quis? Adipisci
                  quod placeat molestias excepturi quaerat corrupti nulla
                  reprehenderit possimus sit, quasi repudiandae delectus iste
                  quidem vero quisquam, laudantium officia nemo! Consequuntur
                  fugit aut cumque quod saepe debitis, perspiciatis quam!
                </p>
                <p>
                  Aliquam nulla illum fugiat repellendus non blanditiis ipsa
                  necessitatibus aut voluptatum aperiam libero, quis accusamus.
                  Quas rem, dolores, minima doloremque nobis blanditiis quam
                  sequi laudantium iste iure, consequuntur cum?
                </p>

                <div className="clearfix"></div>
              </article>
              <div className="buttons">
                <Link
                  to={"/blog/edit/" + article._id}
                  className="btn btn-warning"
                >
                  Editar
                </Link>
                <button
                  onClick={() => {
                    this.deleteArticle(article._id);
                  }}
                  className="btn btn-danger"
                >
                  Eliminar
                </button>
              </div>
              <div className="clearfix"></div>
            </div>
          )}

          {!article && status === "success" && (
            <div id="article">
              <h2 className="subheader">El artículo no existe</h2>
              <p>Intente de nuevo más tarde</p>
            </div>
          )}

          {status === null && (
            <div id="article">
              <h2 className="subheader">Preparando artículo...</h2>
              <p>Espere mientras carga el contenido</p>
            </div>
          )}
        </section>
        <Sidebar />
      </div>
    );
  }
}

// AngularInit/src/app/components/article/article.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';
import Swal from 'sweetalert2';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';
import { Global } from 'src/app/services/global';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {
  @Input() article!: Article;
  public url!: string;

  constructor(
    private articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this._route.params.subscribe(params => {
      let id = params['id'];

      this.articleService.getArticle(id).subscribe(
        response => {
          if(response.article){
            this.article = response.article;
          }else {
            this._router.navigate(['/home']);
          };
          console.log(response);
        },
        error => {
          console.log(error);
          this._router.navigate(['/home']);
        }
      );
    });
  }

  delete(id:string){
    //Alerta
    const swalWithBootstrapButtons = Swal.mixin({
      customClass: {
        confirmButton: 'btn btn-accept',
        cancelButton: 'btn btn-warning'
      },
      buttonsStyling: false
    })
    
    swalWithBootstrapButtons.fire({
      title: '¿Estás seguro que quieres eliminar este artículo?',
      text: "¡No podrás revertir esta acción!",
      icon: 'warning',
      showCancelButton: true,
      confirmButtonText: '¡Sí, elimínalo!',
      cancelButtonText: '¡No, cancelar!',
      reverseButtons: true
    }).then((result) => {
      if (result.isConfirmed) {
        this.articleService.delete(id).subscribe(
          response => {
            this._router.navigate(['/blog']);
            swalWithBootstrapButtons.fire(
              '¡Eliminado!',
              'El artículo ha sido eliminado.',
              'success'
            );
          },
          error => {
            this._router.navigate(['/blog']);
            console.log(error);
          }
        );
      } else if (
        result.dismiss === Swal.DismissReason.cancel
      ) {
        this._router.navigate(['/blog/article', this.article._id]);
        swalWithBootstrapButtons.fire(
          'Acción cancelada',
          '¡El artículo está a salvo!',
          'info'
        );
      }
    });
  }

}

<div class="center">
    <section id="content">
        
        <div id="articles">
            <article class="article-item article-detail" *ngIf="article">
                <h1 class="subheader">{{article.title}}</h1>
                <span class="date">
                    Actualizado: {{article.date | amLocale: 'es' | amTimeAgo}}
                </span>
                <div class="image-wrap">
                    <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
                    <img src="assets/images/default-color.png" alt="{{article.title}}" *ngIf="!article.image">
                </div>
                <p>{{article.content}}</p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure illo, vitae quod possimus, facilis voluptates voluptatum aut non qui iste quia temporibus dolore accusamus odio libero magni fugiat. Hic, a.
                </p>
                <p>
                    Suscipit architecto, velit explicabo nihil asperiores accusantium repellendus cumque maiores! Suscipit a error, sapiente voluptas sit asperiores repellendus aspernatur, autem, temporibus minima nemo maxime fugiat rerum fuga. Voluptatibus, laudantium beatae! Velit cumque culpa dolorem possimus explicabo a reprehenderit, assumenda quo eaque repudiandae, eos omnis autem suscipit, totam tempora!
                </p>
                <p>
                    Dolorum reprehenderit quo dolores maxime architecto exercitationem sequi voluptatem inventore nulla quis? Adipisci quod placeat molestias excepturi quaerat corrupti nulla reprehenderit possimus sit, quasi repudiandae delectus iste quidem vero quisquam, laudantium officia nemo! Consequuntur fugit aut cumque quod saepe debitis, perspiciatis quam!
                </p>
                <p>
                    Aliquam nulla illum fugiat repellendus non blanditiis ipsa necessitatibus aut voluptatum aperiam libero, quis accusamus. Quas rem, dolores, minima doloremque nobis blanditiis quam sequi laudantium iste iure, consequuntur cum?
                </p>

                <div class="buttons">
                    <a [routerLink]="['/blog/edit', article._id]" class="btn btn-danger">Editar</a>
                    <a (click)="delete(article._id)" class="btn btn-warning">Eliminar</a>
                </div>

                <div class="clearfix"></div>
            </article>
        </div>

    </section>
    <app-sidebar></app-sidebar>
</div>
