// vue_init/src/components/Blog.vue
<template>
  <Slider title="Blog" size="slider-small" />
  <div class="center">
    <section id="content">
      <h2 class="subheader">Blog</h2>

      <article
        class="article-item"
        id="article-template"
        v-for="article in articles"
        :key="article._id"
      >
        <div class="image-wrap">
          <img
            :src="url + 'get-image/' + article.image"
            :alt="article.title"
            v-if="article.image"
          />
          <img
            src="../assets/images/default-image.svg"
            :alt="article.title"
            v-else
          />
        </div>
        <h2>{{ article.title }}</h2>
        <span class="date">
          Hace 5 minutos
        </span>
        <a href="article.html">Leer más</a>

        <div class="clearfix"></div>
      </article>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";
import Global from "../Global";

import axios from "axios";

export default {
  name: "Blog",
  components: {
    Slider,
    Sidebar,
  },
  mounted() {
    this.getArticle();
  },
  data() {
    return {
      url: Global.url,
      articles: [],
    };
  },
  methods: {
    getArticle() {
      axios.get(Global.url + "articles").then((res) => {
        if (res.data.status == "success") {
          this.articles = res.data.articles;
        }

        console.log(res.data);
      });
    },
  },
};
</script>

// AngularInit/src/app/components/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { Article } from 'src/app/models/article';
import { ArticleService } from 'src/app/services/article.service';
import { Global } from 'src/app/services/global';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css'],
  providers: [ArticleService]
})
export class BlogComponent implements OnInit {
  blogText = "Blog";
  public articles!: Article[];
  public url!:string;

  constructor(
    private articleService: ArticleService
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {
    this.articleService.getArticles().subscribe(
      response => {
        if(response.articles){
          this.articles = response.articles;
        };
        console.log(response);
      },
      error => {
        console.log(error);
      }
    );
  }

}

<app-slider [title]="blogText" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Blog</h1>
    
    <div id="articles">
      <article class="article-item" *ngFor="let article of articles">
          <div class="image-wrap">
              <img src="{{url + 'get-image/' + article.image}}" alt="{{article.title}}" *ngIf="article.image">
              <img src="assets/images/default-color.png" alt="{{article.title}}" *ngIf="!article.image">
          </div>
          <h2>{{article.title}}</h2>
          <span class="date">
              Hace {{article.date}}
          </span>
          <a href="article.html">Leer más</a>
      </article>
    </div>

  </section>
  
  <app-sidebar></app-sidebar>
</div>
