// vue_init/src/components/Formulario.vue
<template>
  <Slider title="Formulario" size="slider-small" />
  <div class="center">
    <section id="content">
      <h2 class="subheader">Formulario</h2>

      <form class="mid-form" @submit.prevent="showUser()">
        <div class="form-group">
          <label for="nombre">Nombre</label>
          <input type="text" name="nombre" v-model="user.nombre" />
        </div>
        <div class="form-group">
          <label for="apellido">Apellido</label>
          <input type="text" name="apellido" v-model="user.apellido" />
        </div>
        <div class="form-group">
          <label for="bio">Biografia</label>
          <textarea name="bio" v-model="user.bio"></textarea>
        </div>
        <div class="form-group radio-buttons">
          <input
            type="radio"
            name="genero"
            value="Hombre"
            v-model="user.genero"
          />
          Hombre<br />
          <input
            type="radio"
            name="genero"
            value="Mujer"
            v-model="user.genero"
          />
          Mujer<br />
          <input
            type="radio"
            name="genero"
            value="No especificar"
            v-model="user.genero"
          />
          No especificar
        </div>
        <div class="clearfix"></div>
        <input type="submit" value="Enviar" class="btn btn-success" />
      </form>
    </section>
    <Sidebar />
    <div class="clearfix"></div>
  </div>
</template>

<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Formulario",
  components: {
    Slider,
    Sidebar,
  },
  data() {
    return {
      user: {
        nombre: "",
        apellido: "",
        bio: "",
        genero: "",
      },
    };
  },
  methods: {
    showUser() {
      console.log(this.user);
    },
  },
};
</script>

// AngularInit/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
  formText = "Formulario";
  public user: any;

  constructor() {
    this.user = {
      nombre: "",
      apellido: "",
      bio: "",
      genero: ""
    }
  }

  ngOnInit(): void {
  }

  onSubmit(){
    alert("Formulario enviado");
    console.log(this.user);
  }
}

<app-slider [title]="formText" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Formulario</h1>
    {{user.nombre}}<br>
    {{user.apellido}}<br>
    {{user.bio}}<br>
    {{user.genero}}<br>
    <form #userForm="ngForm" class="mid-form" (ngSubmit)="onSubmit()">
      <div class="form-group">
          <label for="nombre">Nombre</label>
          <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre">
      </div>
      <div class="form-group">
          <label for="apellido">Apellido</label>
          <input type="text" name="apellido" #apellido="ngModel" [(ngModel)]="user.apellido">
      </div>
      <div class="form-group">
          <label for="bio">Biografia</label>
          <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio"></textarea>
      </div>
      <div class="form-group radio-buttons">
          <input type="radio" name="genero" value="Hombre" [(ngModel)]="user.genero"> Hombre<br>
          <input type="radio" name="genero" value="Mujer" [(ngModel)]="user.genero"> Mujer<br>
          <input type="radio" name="genero" value="No especificar" [(ngModel)]="user.genero"> No especificar
      </div>
      <div class="clearfix"></div>
      <input type="submit" value="Enviar" class="btn btn-success">
    </form>
  </section>
  
  <app-sidebar></app-sidebar>
</div>
